export const popularVideos = {
  kind: "youtube#videoListResponse",
  etag: "ajTeES8v4PTaD70vsHVItjuTEdM",
  items: [
    {
      kind: "youtube#video",
      etag: "6kFrC4gOgRWuLJob9luRb78AcQ8",
      id: "DUwlGduupRI",
      snippet: {
        publishedAt: "2021-07-06T09:30:02Z",
        channelId: "UC783dnzJqf2ghHp_pFLYbGA",
        title:
          "Filhaal2 Mohabbat | Akshay Kumar Ft Nupur Sanon | Ammy Virk | BPraak | Jaani | Arvindr Khaira",
        description:
          "If 'Filhall' touched your heart, ‘Filhaal 2 - Mohabbat’ will touch your soul. \n\nThe pain of a selfless yet incomplete love story continues with ‘Filhaal 2 - Mohabbat’,\na romantic ballad  that reinstates the fact, true love never dies and if it does, it was never meant to be. \n\nThe beloved pair of Akshay Kumar and Nupur Sanon return as Dr. Kabir Malhotra and Meher Grewal respectively, alongside Ammy Virk in a captivating film directed by Arvindr Khaira. Like always, B Praak delivers heart-melting vocals penned down by ace lyricist Jaani. \n\nDesi Melodies teamed up with Cape of Good Films and Azeem Dayani to create history one more time after making ‘Filhall’.\n\nSubscribe to our channel for more latest songs: http://bit.ly/SubscribeDM-Desi-Melodies\n\nOfficial short video platform partner :- \nhttps://share.mxtakatak.com/zGBadxt3\n\n♪ Full Song Available on ♪ \n\nAudio :- https://ffm.to/filhaal2\n\nFeaturing: Akshay Kumar, Nupur Sanon, and Ammy Virk \nSinger & Music: B Praak \nLyrics & Composer: Jaani \nDirector: Arvindr Khaira \n\nTeam Filhaal 2 - Mohabbat: \nMusic Programming: Gaurav Dev & Kartik Dev  \nMix and Master: Gurjinder Guri & Akaash Bambar \nCreative Director / Steadicam: Amaninder Singh\nSteadicam Assistant :- karan maini \nDOP: Anurag Solanki | Al Ameel  \nEditor: Adele Periera \nGrade: Onkar Singh\nJimmy jib: Manish kumar\nVfx: Shudhanshu jaiswal\nCreative Consultant: Varun Gupta (MAX)\nAssistant Director: Satnam, Sukhman Sukhu, Jais Sivia, Gaurav\nSupporting AD’s :  Viggfx , Monty syan \nChoreography: Alias Kader & Krutik Mazire\nProduction Head: Richa Prinja \nProduction House: Metro Talkies \nLine Producer: Aadesh Gola, Vikrant Kaushik, Aron Paharia (Tash Films Creations)\nProduction Team: Adarsh ,  Sahil, Rahul Dhir, Usama Chauhan, Prashant, and Manish\nMumbai production:- Satish kakade , Anuj tiwari \nDubai Line Producer: Faheem Rahiman (Third Eye Films Dubai)\nProduction Designer: Diksha Sharma\nArt Team: Ashish Moudgil, Priyanka, and Vaishnavi Wadkar\nStylist: Akshay Kumar: Ariko\nMakeup Nupur Sanon: Florian Hurel , Aditya Sharma \nHair Nupur Sanon: Madhav \nStylist Nupur Sanon: Sukriti Grover\nAsst. Stylists: Vani Gupta , Vasudha Gupta\nStylist  Ammy Virk: Lavika Singh\nAsst. Stylists: Kavleen Bakshi, Mini Narula\nBpraak wardrobe design: Mayur Kataria Designs\nMakeup of Junior Artists: Pallavi Kapoor\nCasting of Junior Artist: Arun Bhatia\nViolinist: Manas & Sandeep \nArt Director Mumbai: Akhilesh Suhas \nPhotographer: Arpan Chahal\nLocation: Bptp Amstoria \nGrip: Balarka Arms and Dragon fly \nBTS: Vaibhav bajaj ( BG art)\nSpecial thanks for the Title: Sumeet Kr Tyagi \nSpecial thanks: Snehdip bhaisare\n\nPR Consultant: Hype\nOnline Promotion: Net Media \n\nExecutive Producer: Avadh Nagpal \n\nProject by: Dilraj Nandha \n\n\nLabel: Desi Melodies \nhttps://www.instagram.com/desimelodies/\n\n#filhaal2mohabbat #filhall #Akshaykumar #bpraak #jaani #nupursanon #Arvindrkhaira",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/DUwlGduupRI/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/DUwlGduupRI/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/DUwlGduupRI/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/DUwlGduupRI/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/DUwlGduupRI/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "DM - Desi Melodies",
        tags: [
          "filhall 2",
          "Filhaal 2",
          "Filhaal",
          "mohabbat",
          "Mohabbat karte ho",
          "akshay kumar",
          "nupur sanon",
          "Bpraak",
          "Bpraak filhaal 2",
          "jaani",
          "b praak new song",
          "akshay kumar filhaal",
          "arvindr khaira",
          "ammy virk new song",
          "latest hindi songs",
          "latest punjabi songs",
          "new romantic songs",
          "latest sad song",
          "Filhaal2 mohabbat",
          "Akshay kumar song",
          "Jaani new song",
          "Ik baat batao toh",
          "latest punjabi songs 2021",
          "new punjabi songs 2021",
          "new songs 2021",
          "latest songs 2021",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title:
            "Filhaal2 Mohabbat | Akshay Kumar Ft Nupur Sanon | Ammy Virk | BPraak | Jaani | Arvindr Khaira",
          description:
            "If 'Filhall' touched your heart, ‘Filhaal 2 - Mohabbat’ will touch your soul. \n\nThe pain of a selfless yet incomplete love story continues with ‘Filhaal 2 - Mohabbat’,\na romantic ballad  that reinstates the fact, true love never dies and if it does, it was never meant to be. \n\nThe beloved pair of Akshay Kumar and Nupur Sanon return as Dr. Kabir Malhotra and Meher Grewal respectively, alongside Ammy Virk in a captivating film directed by Arvindr Khaira. Like always, B Praak delivers heart-melting vocals penned down by ace lyricist Jaani. \n\nDesi Melodies teamed up with Cape of Good Films and Azeem Dayani to create history one more time after making ‘Filhall’.\n\nSubscribe to our channel for more latest songs: http://bit.ly/SubscribeDM-Desi-Melodies\n\nOfficial short video platform partner :- \nhttps://share.mxtakatak.com/zGBadxt3\n\n♪ Full Song Available on ♪ \n\nAudio :- https://ffm.to/filhaal2\n\nFeaturing: Akshay Kumar, Nupur Sanon, and Ammy Virk \nSinger & Music: B Praak \nLyrics & Composer: Jaani \nDirector: Arvindr Khaira \n\nTeam Filhaal 2 - Mohabbat: \nMusic Programming: Gaurav Dev & Kartik Dev  \nMix and Master: Gurjinder Guri & Akaash Bambar \nCreative Director / Steadicam: Amaninder Singh\nSteadicam Assistant :- karan maini \nDOP: Anurag Solanki | Al Ameel  \nEditor: Adele Periera \nGrade: Onkar Singh\nJimmy jib: Manish kumar\nVfx: Shudhanshu jaiswal\nCreative Consultant: Varun Gupta (MAX)\nAssistant Director: Satnam, Sukhman Sukhu, Jais Sivia, Gaurav\nSupporting AD’s :  Viggfx , Monty syan \nChoreography: Alias Kader & Krutik Mazire\nProduction Head: Richa Prinja \nProduction House: Metro Talkies \nLine Producer: Aadesh Gola, Vikrant Kaushik, Aron Paharia (Tash Films Creations)\nProduction Team: Adarsh ,  Sahil, Rahul Dhir, Usama Chauhan, Prashant, and Manish\nMumbai production:- Satish kakade , Anuj tiwari \nDubai Line Producer: Faheem Rahiman (Third Eye Films Dubai)\nProduction Designer: Diksha Sharma\nArt Team: Ashish Moudgil, Priyanka, and Vaishnavi Wadkar\nStylist: Akshay Kumar: Ariko\nMakeup Nupur Sanon: Florian Hurel , Aditya Sharma \nHair Nupur Sanon: Madhav \nStylist Nupur Sanon: Sukriti Grover\nAsst. Stylists: Vani Gupta , Vasudha Gupta\nStylist  Ammy Virk: Lavika Singh\nAsst. Stylists: Kavleen Bakshi, Mini Narula\nBpraak wardrobe design: Mayur Kataria Designs\nMakeup of Junior Artists: Pallavi Kapoor\nCasting of Junior Artist: Arun Bhatia\nViolinist: Manas & Sandeep \nArt Director Mumbai: Akhilesh Suhas \nPhotographer: Arpan Chahal\nLocation: Bptp Amstoria \nGrip: Balarka Arms and Dragon fly \nBTS: Vaibhav bajaj ( BG art)\nSpecial thanks for the Title: Sumeet Kr Tyagi \nSpecial thanks: Snehdip bhaisare\n\nPR Consultant: Hype\nOnline Promotion: Net Media \n\nExecutive Producer: Avadh Nagpal \n\nProject by: Dilraj Nandha \n\n\nLabel: Desi Melodies \nhttps://www.instagram.com/desimelodies/\n\n#filhaal2mohabbat #filhall #Akshaykumar #bpraak #jaani #nupursanon #Arvindrkhaira",
        },
        defaultAudioLanguage: "pa",
      },
      contentDetails: {
        duration: "PT5M25S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "81152925",
        likeCount: "2479575",
        dislikeCount: "39162",
        favoriteCount: "0",
        commentCount: "265066",
      },
    },
  ],
  nextPageToken: "CAUQAA",
  pageInfo: {
    totalResults: 200,
    resultsPerPage: 5,
  },
};
